name: Validate Windows Build on PR

on:
  pull_request:
    branches:
      - master # Runs only if the PR targets the master branch

permissions:
  contents: read

jobs:
  validate-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for changelog generation

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x # Ensures correct versioning
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        id: pnpm_cache_path
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm_cache_path.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          ELECTRON_BUILDER_ALLOWED_EXECUTABLES: '*'
        run: pnpm build

    #   - name: Verify Build Output
    #     shell: bash
    #     run: |
    #       if [[ -z $(find dist -type f -name "*.exe") ]]; then
    #         echo "❌ Build output not found! Skipping release."
    #         exit 1
    #       fi
    #       echo "✅ Build output found!"
